#!/usr/bin/env php

<?php

/* Show code reviewer of the case */

$staff1 = '';
$staff2 = '';
$staff3 = '';
$staff4 = '';
$staff5 = '';
$staff6 = '';

$reviewers = array($staff1, $staff2, $staff3, $staff4, $staff5, $staff6);

$case = $argv[1];
$number = $case % count($reviewers);
echo "reviwer: $reviewers[$number]\n\n";
